import * as THREE from './three.module.js';
export function reachable(start,end,links,offline=()=>false,kind='application'){
 const seen=new Set([start]),queue=[start];while(queue.length){const id=queue.shift();if(offline({id}))continue;if(id===end)return true;for(const l of links){if(l.disabled||l.unplugged||l.kind!==kind)continue;const next=l.a===id?l.b:l.b===id?l.a:null;if(next&&!seen.has(next)){seen.add(next);queue.push(next);}}}return false;
}
export function compatible(a,b){return a!==b&&a.medium!=='Internal'&&a.medium===b.medium&&a.speed===b.speed;}
export function createLab(ctx){
 const {camera,canvas,orbitControls,nodes,links,byId,pickables,racks,connect,refreshFaults,isOffline,chooseLink,showEvent,stopFlight,closeDetail}=ctx;
 const $=id=>document.getElementById(id),keys=new Set(),ray=new THREE.Raycaster(),rotation=new THREE.Euler(0,0,0,'YXZ'),forward=new THREE.Vector3(),right=new THREE.Vector3();
 ray.params.Line.threshold=.07;
 let active=false,aim=null,held=null,elapsed=0,selectedCable=null,previous=null,challenge=false;
 const original=links.slice(),events=[];
 document.body.insertAdjacentHTML('beforeend',`<div id="game-bar"><button id="walk-mode">▶ First person</button><button id="lab-toggle">Cable workbench</button><span>WASD walk · Mouse look · E interact</span></div>
 <div id="crosshair" hidden>+</div><div id="walk-prompt" hidden></div>
 <aside id="lab-panel" hidden><div class="lab-head"><b>CABLE LAB</b><button id="lab-close" aria-label="Close cable lab">×</button></div><p>Physical link simulator. Changes affect this session only.</p>
 <label>Cable<select id="lab-cable"></select></label><div class="lab-actions"><button id="lab-trace">Trace ports</button><button id="lab-unplug">Unplug</button><button id="lab-replug">Reconnect</button></div>
 <details><summary>Patch a new cable</summary><p>Select two free ports with the same medium and speed.</p><label>Device A<select id="lab-a"></select></label><label>Port A<select id="lab-pa"></select></label><label>Device B<select id="lab-b"></select></label><label>Port B<select id="lab-pb"></select></label><button id="lab-connect">Connect ports</button></details>
 <label>Probe device<select id="lab-probe"></select></label><button id="lab-ping">Test network and SAN paths</button><output id="lab-result" aria-live="polite">Choose a device and run a path test.</output><div id="lab-health"></div>
 <div class="lab-actions"><button id="lab-challenge">Redundancy challenge</button><button id="lab-reset">Reset cabling</button></div><p id="challenge-note"></p><ol id="lab-events" aria-live="polite"></ol><small>Topology reachability only; VLANs, routing, zoning and protocol convergence are not emulated.</small></aside>`);
 function log(message){events.unshift(message);events.length=Math.min(events.length,5);$('lab-events').replaceChildren(...events.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));showEvent('CABLE LAB',message);}
 function label(l){return `${l.a} ${l.pa.name} ↔ ${l.b} ${l.pb.name}${l.unplugged?' · UNPLUGGED':l.disabled?' · DOWN':' · UP'}`;}
 function options(select,values){select.replaceChildren(...values.map(([value,text])=>new Option(text,value)));}
 function external(l){return l.pa.medium!=='Internal'&&l.pb.medium!=='Internal';}
 function refresh(){const old=$('lab-cable').value;options($('lab-cable'),links.map((l,i)=>[i,label(l)]).filter(([i])=>external(links[i])));if([...$('lab-cable').options].some(o=>o.value===old))$('lab-cable').value=old;fillPorts('a');fillPorts('b');health();}
 function fillPorts(side){const n=byId[$('lab-'+side).value],el=$('lab-p'+side),old=el.value;options(el,n?n.ports.map((p,i)=>[i,p.name+' · '+p.speed+'G '+p.medium]).filter(([i])=>!n.ports[i].link&&n.ports[i].medium!=='Internal'):[]);if([...el.options].some(o=>o.value===old))el.value=old;}
 function unplug(l){if(!l||!external(l))return;if(l.unplugged){log('This cable is already unplugged.');return;}l.unplugged=true;l.pa.link=null;l.pb.link=null;held=l;selectedCable=l;refreshFaults();refresh();log('Unplugged '+l.a+' '+l.pa.name+' ↔ '+l.b+' '+l.pb.name);}
 function replug(l){if(!l?.unplugged){log('Select an unplugged cable first.');return;}if(l.pa.link||l.pb.link){log('A port is occupied. Unplug its replacement cable first.');return;}l.unplugged=false;l.pa.link=l;l.pb.link=l;if(held===l)held=null;refreshFaults();refresh();log('Reconnected '+l.a+' ↔ '+l.b);}
 function health(){const servers=nodes.filter(n=>n.type==='server'&&n.site==='primary');const available=servers.filter(n=>reachable(n.id,'INTERNET',links,x=>isOffline(byId[x.id]))).length;document.querySelector('.live').innerHTML='<i></i> '+(available<servers.length?'SERVICE PATHS DEGRADED':links.some(l=>l.unplugged)?'CABLING MODIFIED':'SYSTEM OPERATIONAL');$('lab-health').textContent=`${available}/${servers.length} primary servers have an Internet path · ${links.filter(l=>l.unplugged).length} cables unplugged`;if(challenge){const n='SERVER-01',up=reachable(n,'INTERNET',links,x=>isOffline(byId[x.id]));const count=links.filter(l=>l.kind==='application'&&(l.a===n||l.b===n)&&!l.disabled).length;$('challenge-note').textContent=count===1&&up?'✓ One network cable removed; the second path is carrying service. Reconnect to restore redundancy.':!up?'Service lost. Reconnect a SERVER-01 network cable to recover.':'Challenge: unplug one SERVER-01 application cable and test its surviving path.';}}
 function test(){refreshFaults();const id=$('lab-probe').value;const off=x=>isOffline(byId[x.id]);const net=reachable(id,'INTERNET',links,off);const a=reachable(id,'CONTROLLER-A',links,off,'storage'),b=reachable(id,'CONTROLLER-B',links,off,'storage');$('lab-result').textContent=`${id}\nInternet path: ${net?'REACHABLE':'UNREACHABLE'}\nSAN controller A: ${a?'REACHABLE':'NO PATH'}\nSAN controller B: ${b?'REACHABLE':'NO PATH'}\nSynthetic graph probe; no real packets are sent.`;health();}
 for(const side of ['a','b','probe'])options($('lab-'+side),nodes.filter(n=>n.type!=='cloud').map(n=>[n.id,n.id]));$('lab-b').selectedIndex=1;$('lab-probe').value='SERVER-01';$('lab-a').onchange=()=>fillPorts('a');$('lab-b').onchange=()=>fillPorts('b');
 $('lab-cable').onchange=()=>selectedCable=links[+$('lab-cable').value];
 $('lab-unplug').onclick=()=>unplug(links[+$('lab-cable').value]);$('lab-replug').onclick=()=>replug(links[+$('lab-cable').value]);$('lab-trace').onclick=()=>{selectedCable=links[+$('lab-cable').value];chooseLink(selectedCable);};
 $('lab-connect').onclick=()=>{const a=byId[$('lab-a').value],b=byId[$('lab-b').value],pa=a.ports[$('lab-pa').value],pb=b.ports[$('lab-pb').value];if(!pa||!pb||a===b||pa.link||pb.link||!compatible(pa,pb)){log('Use two free ports on different devices with matching medium and speed.');return;}const kind=pa.medium==='Fibre Channel'?'storage':pa.name==='MGMT'||pb.name==='MGMT'?'management':'application';if(kind==='storage'&&a.type==='san'&&b.type==='san'){log('Keep SAN fabrics isolated; connect a host or storage controller to a fabric switch.');return;}const l=connect(a.id,b.id,kind,'lab',pa.speed,[pa,pb]);l.custom=true;refreshFaults();refresh();$('lab-cable').value=links.indexOf(l);chooseLink(l);log('Patched '+a.id+' '+pa.name+' ↔ '+b.id+' '+pb.name);};
 $('lab-ping').onclick=test;$('lab-challenge').onclick=()=>{challenge=true;$('lab-probe').value='SERVER-01';const l=links.find(l=>external(l)&&l.kind==='application'&&(l.a==='SERVER-01'||l.b==='SERVER-01'));$('lab-cable').value=links.indexOf(l);chooseLink(l);health();};
 $('lab-reset').onclick=()=>{for(const l of links){if(l.custom){l.unplugged=true;if(l.pa.link===l)l.pa.link=null;if(l.pb.link===l)l.pb.link=null;}}for(const l of original){l.unplugged=false;l.pa.link=l;l.pb.link=l;}held=null;challenge=false;$('challenge-note').textContent='';refreshFaults();refresh();log('Original cabling restored. Use Restore all to clear injected equipment failures.');};
 function panel(open){if(document.pointerLockElement===canvas)document.exitPointerLock();$('lab-panel').hidden=!open;refresh();}
 $('lab-toggle').onclick=()=>panel($('lab-panel').hidden);$('lab-close').onclick=()=>panel(false);
 function lock(){try{const result=canvas.requestPointerLock?.();result?.catch(()=>log('Mouse capture unavailable. Drag on the scene to look around; WASD still moves.'));}catch{log('Drag to look around; WASD moves.');}}
 function enter(){previous={position:camera.position.clone(),quaternion:camera.quaternion.clone(),target:orbitControls.target.clone(),fov:camera.fov};active=true;stopFlight();closeDetail();orbitControls.enabled=false;camera.position.set(-3,4.4,9);camera.lookAt(-3,4.4,0);rotation.setFromQuaternion(camera.quaternion,'YXZ');camera.fov=68;camera.updateProjectionMatrix();document.body.classList.add('walking');$('crosshair').hidden=false;$('walk-prompt').hidden=false;$('walk-mode').textContent='↗ Overview';panel(false);lock();}
 function exit(){if(!active)return;active=false;keys.clear();if(document.pointerLockElement===canvas)document.exitPointerLock();document.body.classList.remove('walking');$('crosshair').hidden=true;$('walk-prompt').hidden=true;$('walk-mode').textContent='▶ First person';camera.position.copy(previous.position);camera.quaternion.copy(previous.quaternion);camera.fov=previous.fov;camera.updateProjectionMatrix();orbitControls.target.copy(previous.target);orbitControls.enabled=true;orbitControls.update();}
 $('walk-mode').onclick=()=>active?exit():enter();
 let dragging=false;canvas.addEventListener('pointerdown',()=>{if(active)dragging=true;});addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('click',()=>{if(active&&$('lab-panel').hidden&&!document.pointerLockElement)lock();});
 document.addEventListener('mousemove',e=>{if(!active||!(document.pointerLockElement===canvas||dragging))return;rotation.y-=e.movementX*.002;rotation.x=THREE.MathUtils.clamp(rotation.x-e.movementY*.002,-1.45,1.45);camera.quaternion.setFromEuler(rotation);});
 addEventListener('keydown',e=>{if(!active||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','shift','q','z','e','f'].includes(k)){e.preventDefault();keys.add(k);}if(e.repeat)return;if(k==='e'){if(aim?.port?.link)unplug(aim.port.link);else if(aim?.link)unplug(aim.link);else if(held&&aim?.port&&(aim.port===held.pa||aim.port===held.pb))replug(held);else panel(true);}if(k==='f'){if(aim?.node)$('lab-probe').value=aim.node.id;panel(true);test();}if(k==='escape')keys.clear();});
 addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();dragging=false;});document.addEventListener('pointerlockchange',()=>keys.clear());
 function clear(x,z){return x>-18&&x<38&&z>-14&&z<18&&!racks.some(r=>Math.abs(x-r.x)<2.18&&Math.abs(z)<3.7);}
 function teleport(n){camera.position.set(n.pos.x,THREE.MathUtils.clamp(n.pos.y,1,13),n.ports.some(p=>p.side==='rear')?-8:8);camera.lookAt(n.pos);rotation.setFromQuaternion(camera.quaternion,'YXZ');}
 function update(dt){elapsed+=dt;if(elapsed>.5){health();elapsed=0;}if(!active)return;if(!$('lab-panel').hidden)return;camera.getWorldDirection(forward);forward.y=0;forward.normalize();right.crossVectors(forward,camera.up).normalize();const delta=new THREE.Vector3().addScaledVector(forward,(keys.has('w')?1:0)-(keys.has('s')?1:0)).addScaledVector(right,(keys.has('d')?1:0)-(keys.has('a')?1:0));if(delta.lengthSq())delta.normalize().multiplyScalar(dt*(keys.has('shift')?11:5));if(clear(camera.position.x+delta.x,camera.position.z))camera.position.x+=delta.x;if(clear(camera.position.x,camera.position.z+delta.z))camera.position.z+=delta.z;camera.position.y=THREE.MathUtils.clamp(camera.position.y+dt*4*((keys.has('q')?1:0)-(keys.has('z')?1:0)),1,13);
 ray.setFromCamera(new THREE.Vector2(0,0),camera);ray.far=4;const hits=ray.intersectObjects(pickables,false).filter(h=>h.object.visible&&!h.object.userData.link?.unplugged);const h=hits.find(h=>h.object.userData.portIndices)||hits[0];aim=h?{...h.object.userData}:null;if(aim?.portIndices&&h.instanceId!==undefined)aim.port=aim.node.ports[aim.portIndices[h.instanceId]];
 $('walk-prompt').textContent=aim?.port?`${aim.node.id} · ${aim.port.name} · ${aim.port.link?'E unplug':held&&(aim.port===held.pa||aim.port===held.pb)?'E reconnect held cable':'E open patch panel'} · F test`:aim?.link?`${aim.link.a} ↔ ${aim.link.b} · E unplug`:aim?.node?`${aim.node.id} · E ports / F test`:'WASD move · Shift faster · Q/Z raise/lower inspection height · Esc release mouse · E workbench';}
 refresh();return {get active(){return active;},update,exit,teleport};
}
