import { createServiceKit } from './service-kit.js';
import * as THREE from './three.module.js';
export function reachable(start,end,links,offline=()=>false,kind='application'){
 const seen=new Set([start]),queue=[start];while(queue.length){const id=queue.shift();if(offline({id}))continue;if(id===end)return true;for(const l of links){if(l.disabled||l.unplugged||l.kind!==kind)continue;const next=l.a===id?l.b:l.b===id?l.a:null;if(next&&!seen.has(next)){seen.add(next);queue.push(next);}}}return false;
}
export function compatible(a,b){return a!==b&&a.medium!=='Internal'&&a.medium===b.medium&&a.speed===b.speed;}
export function createLab(ctx){
 const {scene,camera,canvas,orbitControls,nodes,links,byId,pickables,racks,connect,refreshFaults,isOffline,chooseLink,showEvent,stopFlight,closeDetail}=ctx;
 const $=id=>document.getElementById(id),keys=new Set(),ray=new THREE.Raycaster(),rotation=new THREE.Euler(0,0,0,'YXZ'),forward=new THREE.Vector3(),right=new THREE.Vector3();
 ray.params.Line.threshold=.07;
 let savedWalk=null;let active=false,aim=null,held=null,elapsed=0,selectedCable=null,previous=null,challenge=false;
 const original=links.slice(),events=[];
 const kit=createServiceKit({scene,camera,nodes,pickables,isOffline,links,byId});
 const velocity=new THREE.Vector3();let elevated=false,crouched=false,walkTime=0;const STANDING=9.7,CROUCH=5.9;
 const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
 document.body.insertAdjacentHTML('beforeend',`<div id="game-bar"><div id="mode-switch" role="group" aria-label="Experience mode"><button id="inspect-mode" aria-pressed="true">Inspect</button><button id="walk-mode" aria-pressed="false">Gameplay</button></div><button id="lab-toggle">Cable workbench</button></div>
 <div id="crosshair" hidden>+</div><div id="walk-prompt" hidden></div>
 <aside id="lab-panel" hidden><div class="lab-head"><b>CABLE LAB</b><button id="lab-close" aria-label="Close cable lab">×</button></div><p>Physical link simulator. Changes affect this session only.</p>
 <label>Cable<select id="lab-cable"></select></label><div class="lab-actions"><button id="lab-trace">Trace ports</button><button id="lab-unplug">Unplug</button><button id="lab-replug">Reconnect</button></div>
 <details><summary>Patch a new cable</summary><p>Select two free ports with the same medium and speed.</p><label>Device A<select id="lab-a"></select></label><label>Port A<select id="lab-pa"></select></label><label>Device B<select id="lab-b"></select></label><label>Port B<select id="lab-pb"></select></label><button id="lab-connect">Connect ports</button></details>
 <label>Probe device<select id="lab-probe"></select></label><button id="lab-ping">Test network and SAN paths</button><output id="lab-result" aria-live="polite">Choose a device and run a path test.</output><div id="lab-health"></div>
 <div class="lab-actions"><button id="lab-challenge">Redundancy challenge</button><button id="lab-reset">Reset cabling</button></div><p id="challenge-note"></p><ol id="lab-events" aria-live="polite"></ol><small>Topology reachability only; VLANs, routing, zoning and protocol convergence are not emulated.</small></aside>`);
 document.body.append($('event'));
 function log(message){events.unshift(message);events.length=Math.min(events.length,5);$('lab-events').replaceChildren(...events.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));showEvent('CABLE LAB',message);}
 function label(l){return `${l.a} ${l.pa.name} ↔ ${l.b} ${l.pb.name}${l.unplugged?' · UNPLUGGED':l.disabled?' · DOWN':' · UP'}`;}
 function options(select,values){select.replaceChildren(...values.map(([value,text])=>new Option(text,value)));}
 function external(l){return l.pa.medium!=='Internal'&&l.pb.medium!=='Internal';}
 function refresh(){const old=$('lab-cable').value;options($('lab-cable'),links.map((l,i)=>[i,label(l)]).filter(([i])=>external(links[i])));if([...$('lab-cable').options].some(o=>o.value===old))$('lab-cable').value=old;fillPorts('a');fillPorts('b');health();}
 function fillPorts(side){const n=byId[$('lab-'+side).value],el=$('lab-p'+side),old=el.value;options(el,n?n.ports.map((p,i)=>[i,p.name+' · '+p.speed+'G '+p.medium]).filter(([i])=>!n.ports[i].link&&!n.ports[i].service&&n.ports[i].medium!=='Internal'):[]);if([...el.options].some(o=>o.value===old))el.value=old;}
 function unplug(l){if(!l||!external(l))return;if(l.unplugged){log('This cable is already unplugged.');return;}l.unplugged=true;l.pa.link=null;l.pb.link=null;held=l;selectedCable=l;refreshFaults();refresh();log('Unplugged '+l.a+' '+l.pa.name+' ↔ '+l.b+' '+l.pb.name);}
 function replug(l){if(!l?.unplugged){log('Select an unplugged cable first.');return;}if(l.pa.link||l.pb.link){log('A port is occupied. Unplug its replacement cable first.');return;}l.unplugged=false;l.pa.link=l;l.pb.link=l;if(held===l)held=null;refreshFaults();refresh();log('Reconnected '+l.a+' ↔ '+l.b);}
 function health(){const servers=nodes.filter(n=>n.type==='server'&&n.site==='primary');const available=servers.filter(n=>reachable(n.id,'INTERNET',links,x=>isOffline(byId[x.id]))).length;document.querySelector('.live').innerHTML='<i></i> '+(available<servers.length?'SERVICE PATHS DEGRADED':links.some(l=>l.unplugged)?'CABLING MODIFIED':'SYSTEM OPERATIONAL');$('lab-health').textContent=`${available}/${servers.length} primary servers have an Internet path · ${links.filter(l=>l.unplugged).length} cables unplugged`;if(challenge){const n='SERVER-01',up=reachable(n,'INTERNET',links,x=>isOffline(byId[x.id]));const count=links.filter(l=>l.kind==='application'&&(l.a===n||l.b===n)&&!l.disabled).length;$('challenge-note').textContent=count===1&&up?'✓ One network cable removed; the second path is carrying service. Reconnect to restore redundancy.':!up?'Service lost. Reconnect a SERVER-01 network cable to recover.':'Challenge: unplug one SERVER-01 application cable and test its surviving path.';}}
 function test(){refreshFaults();const id=$('lab-probe').value;const off=x=>isOffline(byId[x.id]);const net=reachable(id,'INTERNET',links,off);const a=reachable(id,'CONTROLLER-A',links,off,'storage'),b=reachable(id,'CONTROLLER-B',links,off,'storage');$('lab-result').textContent=`${id}\nInternet path: ${net?'REACHABLE':'UNREACHABLE'}\nSAN controller A: ${a?'REACHABLE':'NO PATH'}\nSAN controller B: ${b?'REACHABLE':'NO PATH'}\nSynthetic graph probe; no real packets are sent.`;health();}
 for(const side of ['a','b','probe'])options($('lab-'+side),nodes.filter(n=>n.type!=='cloud').map(n=>[n.id,n.id]));$('lab-b').selectedIndex=1;$('lab-probe').value='SERVER-01';$('lab-a').onchange=()=>fillPorts('a');$('lab-b').onchange=()=>fillPorts('b');
 $('lab-cable').onchange=()=>selectedCable=links[+$('lab-cable').value];
 $('lab-unplug').onclick=()=>unplug(links[+$('lab-cable').value]);$('lab-replug').onclick=()=>replug(links[+$('lab-cable').value]);$('lab-trace').onclick=()=>{selectedCable=links[+$('lab-cable').value];chooseLink(selectedCable);};
 $('lab-connect').onclick=()=>{const a=byId[$('lab-a').value],b=byId[$('lab-b').value],pa=a.ports[$('lab-pa').value],pb=b.ports[$('lab-pb').value];if(!pa||!pb||a===b||pa.link||pb.link||!compatible(pa,pb)){log('Use two free ports on different devices with matching medium and speed.');return;}const kind=pa.medium==='Fibre Channel'?'storage':pa.name==='MGMT'||pb.name==='MGMT'?'management':'application';if(kind==='storage'&&a.type==='san'&&b.type==='san'){log('Keep SAN fabrics isolated; connect a host or storage controller to a fabric switch.');return;}const l=connect(a.id,b.id,kind,'lab',pa.speed,[pa,pb]);l.custom=true;refreshFaults();refresh();$('lab-cable').value=links.indexOf(l);chooseLink(l);log('Patched '+a.id+' '+pa.name+' ↔ '+b.id+' '+pb.name);};
 $('lab-ping').onclick=test;$('lab-challenge').onclick=()=>{challenge=true;$('lab-probe').value='SERVER-01';const l=links.find(l=>external(l)&&l.kind==='application'&&(l.a==='SERVER-01'||l.b==='SERVER-01'));$('lab-cable').value=links.indexOf(l);chooseLink(l);health();};
 $('lab-reset').onclick=()=>{for(const l of links){if(l.custom){l.unplugged=true;if(l.pa.link===l)l.pa.link=null;if(l.pb.link===l)l.pb.link=null;}}for(const l of original){l.unplugged=false;l.pa.link=l;l.pb.link=l;}held=null;challenge=false;$('challenge-note').textContent='';refreshFaults();refresh();log('Original cabling restored. Use Restore all to clear injected equipment failures.');};
 function panel(open){if(active&&open)return;keys.clear();velocity.set(0,0,0);if(open)kit.hide();if(document.pointerLockElement===canvas)document.exitPointerLock();$('lab-panel').hidden=!open;refresh();}
 $('lab-toggle').onclick=()=>panel($('lab-panel').hidden);$('lab-close').onclick=()=>panel(false);
 function lock(){try{const result=canvas.requestPointerLock?.();result?.catch(()=>log('Mouse capture unavailable. Drag on the scene to look around; WASD still moves.'));}catch{log('Drag to look around; WASD moves.');}}
 function enter(){if(active)return;previous={position:camera.position.clone(),quaternion:camera.quaternion.clone(),target:orbitControls.target.clone(),fov:camera.fov};active=true;stopFlight();closeDetail();orbitControls.enabled=false;camera.position.set(-3,STANDING,10);camera.lookAt(-3,STANDING,0);rotation.setFromQuaternion(camera.quaternion,'YXZ');if(savedWalk){camera.position.copy(savedWalk.position);camera.quaternion.copy(savedWalk.quaternion);rotation.setFromQuaternion(camera.quaternion,'YXZ');}camera.fov=78;elevated=false;crouched=false;velocity.set(0,0,0);camera.updateProjectionMatrix();document.body.classList.add('walking');$('crosshair').hidden=false;$('walk-prompt').hidden=false;$('inspect-mode').setAttribute('aria-pressed','false');$('walk-mode').setAttribute('aria-pressed','true');$('terminal').hidden=true;$('event').hidden=true;panel(false);canvas.focus();lock();}
 function exit(){if(!active)return;savedWalk={position:camera.position.clone(),quaternion:camera.quaternion.clone()};active=false;kit.hide();keys.clear();velocity.set(0,0,0);if(document.pointerLockElement===canvas)document.exitPointerLock();document.body.classList.remove('walking');$('crosshair').hidden=true;$('walk-prompt').hidden=true;$('inspect-mode').setAttribute('aria-pressed','true');$('walk-mode').setAttribute('aria-pressed','false');$('lab-panel').hidden=true;camera.position.copy(previous.position);camera.quaternion.copy(previous.quaternion);camera.fov=previous.fov;camera.updateProjectionMatrix();orbitControls.target.copy(previous.target);orbitControls.enabled=true;orbitControls.update();}
 $('walk-mode').onclick=enter;$('inspect-mode').onclick=exit;
 let dragging=false;canvas.addEventListener('pointerdown',()=>{if(active)dragging=true;});addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('click',()=>{if(active&&$('lab-panel').hidden&&!kit.isOpen&&!document.pointerLockElement)lock();});
 document.addEventListener('mousemove',e=>{if(!active||kit.isOpen||!(document.pointerLockElement===canvas||dragging))return;rotation.y-=e.movementX*.002;rotation.x=THREE.MathUtils.clamp(rotation.x-e.movementY*.002,-1.45,1.45);camera.quaternion.setFromEuler(rotation);});
 addEventListener('keydown',e=>{
 const k=e.key.toLowerCase();if(k==='escape'&&kit.isOpen){kit.hide();keys.clear();return;}
 if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;
 if(k==='m'){e.preventDefault();active?exit():enter();return;}
 if(k==='tab'&&active){e.preventDefault();keys.clear();velocity.set(0,0,0);panel(false);kit.isOpen?kit.hide():kit.show();return;}
 if(!active||kit.isOpen)return;
 if(['w','a','s','d','shift','q','c','e','f','0','1','2','x'].includes(k)){e.preventDefault();keys.add(k);}if(e.repeat)return;
 if(['0','1','2'].includes(k)){kit.equip(+k);return;}
 if(k==='q'){elevated=!elevated;crouched=false;}
 if(k==='c'){crouched=true;elevated=false;}
 if(k==='x'){kit.disconnect();return;}
 if(k==='e'){if(kit.interact(aim)){keys.clear();velocity.set(0,0,0);return;}if(kit.slot!==0){showEvent('AIM AT A SERVICE PORT','1 Console → orange CONSOLE · 2 LAN → blue SERVICE LAN');return;}if(aim?.port?.link)unplug(aim.port.link);else if(aim?.link)unplug(aim.link);else if(held&&aim?.port&&(aim.port===held.pa||aim.port===held.pb))replug(held);else showEvent('HANDS','Aim at a cable to unplug or at the original port to reconnect.');}
 if(k==='f'){keys.clear();kit.show();}
 if(k==='escape')keys.clear();
 });
 addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key.toLowerCase()==='c')crouched=false;});addEventListener('blur',()=>{keys.clear();crouched=false;velocity.set(0,0,0);dragging=false;});document.addEventListener('pointerlockchange',()=>{keys.clear();crouched=false;velocity.set(0,0,0);});
 function clear(x,z){return x>-22&&x<42&&z>-18&&z<22&&!racks.some(r=>Math.abs(x-r.x)<2.1&&Math.abs(z)<3.65)&&!(Math.abs(x-15)<1.7&&Math.abs(z-8)<1.4)&&!racks.some(r=>nodes.some(n=>n.rack===r.id&&(n.type==='server'||n.type==='gpu'))&&Math.abs(x-r.x)<1.55&&Math.abs(z-5.15)<.95);}
 function teleport(n){elevated=false;crouched=false;camera.position.set(n.pos.x,STANDING,n.ports.some(p=>p.side==='rear')?-8:8);camera.lookAt(n.pos);rotation.setFromQuaternion(camera.quaternion,'YXZ');}
 function update(dt){dt=Math.min(dt,.05);kit.update(active);elapsed+=dt;if(elapsed>.5){health();elapsed=0;}if(!active)return;if(!$('lab-panel').hidden||kit.isOpen){keys.clear();velocity.set(0,0,0);return;}
 camera.getWorldDirection(forward);forward.y=0;forward.normalize();right.crossVectors(forward,camera.up).normalize();
 const direction=new THREE.Vector3().addScaledVector(forward,(keys.has('w')?1:0)-(keys.has('s')?1:0)).addScaledVector(right,(keys.has('d')?1:0)-(keys.has('a')?1:0));
 const speed=crouched?4.8:keys.has('shift')?21:11;direction.normalize().multiplyScalar(speed);velocity.lerp(direction,1-Math.exp(-dt*18));
 const dx=velocity.x*dt,dz=velocity.z*dt;if(clear(camera.position.x+dx,camera.position.z))camera.position.x+=dx;else velocity.x=0;if(clear(camera.position.x,camera.position.z+dz))camera.position.z+=dz;else velocity.z=0;
 const moving=velocity.length()>1;walkTime+=dt*(keys.has('shift')?13:9);const eye=crouched?CROUCH:elevated?13.4:STANDING;const bob=!reducedMotion&&moving&&!elevated?Math.sin(walkTime)*.045:0;camera.position.y=THREE.MathUtils.lerp(camera.position.y,eye+bob,1-Math.exp(-dt*12));const fov=keys.has('shift')&&moving&&!crouched?83:78;camera.fov=THREE.MathUtils.lerp(camera.fov,fov,1-Math.exp(-dt*8));camera.updateProjectionMatrix();
 $('stance').textContent=crouched?'CROUCHED':elevated?'UPPER INSPECTION':keys.has('shift')&&moving?'SPRINTING':'STANDING';
 ray.setFromCamera(new THREE.Vector2(0,0),camera);ray.far=7;const hits=ray.intersectObjects(pickables,false).filter(h=>h.object.visible&&!h.object.userData.link?.unplugged);const nearest=hits[0]?.distance??0;const h=hits.find(h=>(h.object.userData.servicePort||h.object.userData.portIndices)&&h.distance<nearest+.5)||hits[0];aim=h?{...h.object.userData}:null;if(aim?.portIndices&&h.instanceId!==undefined)aim.port=aim.node.ports[aim.portIndices[h.instanceId]];
 $('walk-prompt').textContent=aim?.monitor?'SERVER MONITOR + KEYBOARD · E inspect':aim?.laptop?'FIELD LAPTOP · E open':aim?.port?.service?`${aim.node.id} · ${aim.port.name} · ${kit.slot===1?'CONSOLE':kit.slot===2?'LAN':'HANDS'} · E connect laptop`:kit.slot&&aim?.node?`${aim.node.id} · E attach ${kit.slot===1?'console':'service LAN'} cable`:aim?.port?`${aim.node.id} · ${aim.port.name} · ${aim.port.link?'E unplug':held&&(aim.port===held.pa||aim.port===held.pb)?'E reconnect':'FREE PORT'}`:aim?.link?`${aim.link.a} ↔ ${aim.link.b} · E unplug`:'WASD walk · Shift sprint · Hold C crouch · Q upper view · 1 Console / 2 LAN · Tab laptop';}

 refresh();return {enter,get active(){return active;},update,exit,teleport,kit};
}
