import * as THREE from './three.module.js';
export function createMultiplayer({scene,camera,world,network,onWorld,closePanels}){
 const $=id=>document.getElementById(id);let selfID=null,token=null,revision=0,stream=null,healthy=false,busy=false,elapsed=0,modal=false;const models=new Map();
 document.getElementById('game-bar').insertAdjacentHTML('beforeend','<button id="lan-button">LAN co-op · 1/4</button>');
 document.body.insertAdjacentHTML('beforeend',`<section id="lan-panel" hidden aria-label="LAN multiplayer"><div class="lab-head"><b>LAN CO-OP · 4 PLAYERS MAX</b><button id="lan-close">×</button></div><p id="lan-status">Open the site from the local host computer’s server address to play together.</p><label>Player name<input id="lan-name" maxlength="20" value="Engineer"></label><label>Room code<input id="lan-code" maxlength="32" autocomplete="off" placeholder="Ask the host"></label><div class="lab-actions"><button id="lan-join">Join room</button><button id="lan-leave" hidden>Leave room</button></div><ol id="lan-roster"></ol><div id="lan-events"></div><details><summary>Host a local room</summary><p>Use the LAN package. Install Node.js, open its folder in Terminal, and run:</p><code>node lan/server.mjs</code><p>Share the address and room code printed there. Everyone must use that address on the same LAN. The room supports four players including the host. No internet matchmaking.</p></details></section>`);
 function visible(open){modal=open;$('lan-panel').hidden=!open;if(open){closePanels();if(document.pointerLockElement)document.exitPointerLock();}}
 $('lan-button').onclick=()=>visible(!modal);$('lan-close').onclick=()=>visible(false);
 function state(data){if(data.world&&data.revision>=revision){revision=data.revision;world.restore(data.world);onWorld();}if(data.events){$('lan-events').replaceChildren(...data.events.map(t=>{const p=document.createElement('p');p.textContent=t;return p;}));}}
 function avatar(p){const g=new THREE.Group(),body=new THREE.Group();g.add(body);const shirt=new THREE.MeshStandardMaterial({color:p.color,roughness:.75}),boots=new THREE.MeshStandardMaterial({color:0x182631}),skin=new THREE.MeshStandardMaterial({color:0xbc9273});
 function box(w,h,d,x,y,z,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);body.add(m);return m;}
 box(2.2,3.7,1.25,0,5.8,0,shirt);box(1.85,1.9,1.65,0,9,0,skin);box(1.92,.36,1.72,0,10,0,shirt);const legs=[box(.8,3.2,.95,-.65,2.2,0,boots),box(.8,3.2,.95,.65,2.2,0,boots)],arms=[box(.58,3,.7,-1.43,5.8,0,shirt),box(.58,3,.7,1.43,5.8,0,shirt)];box(.75,.45,1.25,-.65,.5,.13,boots);box(.75,.45,1.25,.65,.5,.13,boots);const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#e4f4ff';ctx.font='bold 42px sans-serif';ctx.textAlign='center';ctx.fillText(p.name,256,64);const label=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));label.position.y=11.3;label.scale.set(4.5,.85,1);g.add(label);scene.add(g);return {g,body,label,legs,arms,target:new THREE.Vector3(p.pose.x,0,p.pose.z),yaw:p.pose.yaw,crouch:p.pose.crouched,last:p.pose};}
 function dispose(m){scene.remove(m.g);m.g.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});}
 function players(list){const present=new Set();for(const p of list){if(p.id===selfID)continue;present.add(p.id);let model=models.get(p.id);if(!model){model=avatar(p);model.g.position.copy(model.target);models.set(p.id,model);}model.target.set(p.pose.x,Math.max(0,p.pose.y-(p.pose.crouched?5.9:9.7)),p.pose.z);model.yaw=p.pose.yaw;model.crouch=p.pose.crouched;model.g.visible=p.pose.active;}
 for(const [id,m]of models)if(!present.has(id)){dispose(m);models.delete(id);}$('lan-roster').replaceChildren(...list.map(p=>{const li=document.createElement('li');li.textContent=p.name+(p.id===selfID?' (you)':'')+(p.pose.active?' · in game':' · inspecting');return li;}));$('lan-button').textContent=token?`LAN co-op · ${list.length}/4`:'LAN co-op · 1/4';}
 async function post(route,body){const res=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-Player-Token':token}:{})},body:JSON.stringify(body)});const data=await res.json();if(!res.ok){if(data.world)state(data);throw new Error(data.error||'LAN request failed');}return data;}
 async function send(action){if(!token||!healthy)return 'LAN connection unavailable. Wait for reconnection or leave the room.';try{const data=await post('action',{revision,action});state(data);return data.message;}catch(e){$('lan-status').textContent=e.message;return e.message;}}
 function leave(){if(token)post('leave',{}).catch(()=>{});stream?.close();stream=null;token=null;healthy=false;network.setSubmit(null);for(const m of models.values())dispose(m);models.clear();$('lan-leave').hidden=true;$('lan-join').disabled=false;$('lan-button').textContent='LAN co-op · 1/4';$('lan-roster').replaceChildren();$('lan-status').textContent='Single player. Current world changes remain in this tab.';onWorld();}
 $('lan-leave').onclick=leave;
 $('lan-join').onclick=async()=>{if(token)return;$('lan-join').disabled=true;try{const check=await fetch('/api/room');if(!check.ok)throw new Error('Local server not running here. Open the host address from the LAN package.');const info=await check.json();if(info.protocol!=='infra-lan-v1')throw new Error('Use the LAN server address.');const data=await post('join',{name:$('lan-name').value,code:$('lan-code').value.trim().toUpperCase()});token=data.token;selfID=data.id;revision=data.revision;state(data);players(data.players);network.setSubmit(send);healthy=true;$('lan-leave').hidden=false;$('lan-status').textContent='Connected. Players share cables, VLANs, port states and workloads.';stream=new EventSource('/api/events?token='+encodeURIComponent(token));stream.addEventListener('players',e=>players(JSON.parse(e.data)));stream.addEventListener('world',e=>state(JSON.parse(e.data)));stream.onopen=()=>{healthy=true;$('lan-status').textContent='Connected · shared room state';};stream.onerror=()=>{healthy=false;$('lan-status').textContent='Connection interrupted. Reconnecting… Leave and rejoin if the host restarted.';};onWorld();}catch(e){$('lan-status').textContent=e.message;$('lan-join').disabled=false;}};
 function update(dt,active,crouched){elapsed+=dt;for(const m of models.values()){const distance=m.g.position.distanceTo(m.target);m.g.position.lerp(m.target,1-Math.exp(-dt*14));const current=m.g.rotation.y,difference=Math.atan2(Math.sin(m.yaw-current),Math.cos(m.yaw-current));m.g.rotation.y+=difference*(1-Math.exp(-dt*14));m.body.scale.y=THREE.MathUtils.lerp(m.body.scale.y,m.crouch?.61:1,1-Math.exp(-dt*12));m.label.position.y=m.crouch?7.2:11.3;const swing=distance>.08?Math.sin(performance.now()/100)*.28:0;m.legs[0].rotation.x=swing;m.legs[1].rotation.x=-swing;m.arms[0].rotation.x=-swing;m.arms[1].rotation.x=swing;}
 if(token&&elapsed>.12&&!busy){elapsed=0;busy=true;const rotation=new THREE.Euler().setFromQuaternion(camera.quaternion,'YXZ');post('pose',{pose:{x:camera.position.x,y:camera.position.y,z:camera.position.z,yaw:rotation.y,crouched,active}}).catch(e=>{$('lan-status').textContent=e.message;healthy=false;}).finally(()=>busy=false);}}
 return {get connected(){return !!token;},get isOpen(){return modal;},send,update,leave,hide:()=>visible(false)};
}
