import * as THREE from './three.module.js';
export function serviceCommand(input,session,ctx){
 const {nodes,links,isOffline,byId}=ctx,n=session?.node;if(!n)return 'No connection. Equip 1 Console or 2 LAN, aim at a service port, and press E.';
 if(isOffline(n))return n.id+' is offline. No response from the simulated device.';
 const command=input.trim().toLowerCase();
 if(command==='help')return 'help\nshow system\nshow interfaces\nshow links\nshow storage\nping DEVICE-ID\nclear\nRead-only simulation; vendor operating systems are not emulated.';
 if(command==='show system'||command==='show version')return `${n.id}\n${n.model}\nRack ${n.rack} · ${n.units??'—'}U\nPower: ON\nSession: ${session.mode}\nSimulated service session`;
 if(command==='show interfaces'||command==='show links')return n.ports.map(p=>`${p.name.padEnd(22)} ${p.medium.padEnd(14)} ${p.service?(session.port===p?'LAPTOP ATTACHED':'AVAILABLE'):p.link?(p.link.disabled||p.link.unplugged?'DOWN':'UP'):'NO CABLE'}${p.link?' → '+(p.link.a===n.id?p.link.b:p.link.a):''}`).join('\n');
 if(command==='show storage')return links.filter(l=>l.kind==='storage'&&(l.a===n.id||l.b===n.id)).map(l=>`${l.a} ↔ ${l.b}: ${l.disabled||l.unplugged?'DOWN':'UP'}`).join('\n')||'No directly attached SAN links on this device.';
 if(command.startsWith('ping ')){const destination=input.trim().split(/\s+/)[1]?.toUpperCase();if(!byId[destination])return 'Unknown device. Use its topology name, for example CORE-A or SERVER-01.';const visited=new Set([n.id]),q=[n.id];while(q.length){const id=q.shift();if(isOffline(byId[id]))continue;if(id===destination)return `Graph probe ${destination}: REACHABLE\nSynthetic result; no ICMP or IP configuration is emulated.`;for(const l of links){if(l.kind!=='application'||l.disabled||l.unplugged)continue;const other=l.a===id?l.b:l.b===id?l.a:null;if(other&&!visited.has(other)){visited.add(other);q.push(other);}}}return `Graph probe ${destination}: NO APPLICATION PATH`;}
 return 'Unknown command. Type help.';
}
export function createServiceKit(ctx){
 const {scene,camera,nodes,pickables,isOffline,links,byId}=ctx,$=id=>document.getElementById(id);
 let session=null,slot=0,open=false,walking=false,tether=null;
 const dark=new THREE.MeshStandardMaterial({color:0x26313b,roughness:.5,metalness:.55}),silver=new THREE.MeshStandardMaterial({color:0x84939d,roughness:.4,metalness:.7}),screenMat=new THREE.MeshBasicMaterial({color:0x12364d}),keyMat=new THREE.MeshStandardMaterial({color:0x101820});
 const geo=new THREE.BoxGeometry(1,1,1);
 function box(parent,w,h,d,x,y,z,mat=dark){const m=new THREE.Mesh(geo,mat);m.scale.set(w,h,d);m.position.set(x,y,z);parent.add(m);return m;}
 function text(parent,message,x,y,z,w=1.6){const c=document.createElement('canvas');c.width=512;c.height=128;const g=c.getContext('2d');g.fillStyle='#9aeacf';g.font='bold 30px monospace';g.textAlign='center';g.fillText(message,256,70);const texture=new THREE.CanvasTexture(c),m=new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),new THREE.MeshBasicMaterial({map:texture,transparent:true}));m.position.set(x,y,z);parent.add(m);return m;}
 function computer(parent,x,y,z,scale=1){const g=new THREE.Group();g.position.set(x,y,z);g.scale.setScalar(scale);parent.add(g);box(g,1.5,.09,1,0,0,0,silver);box(g,1.48,.94,.08,0,.49,-.43);box(g,1.32,.75,.015,0,.51,-.379,screenMat);text(g,'FIELD TERMINAL',0,.51,-.365,1.15);for(let row=0;row<4;row++)for(let col=0;col<12;col++)box(g,.088,.015,.09,-.58+col*.105,.056,-.25+row*.11,keyMat);box(g,.4,.012,.2,0,.059,.3,keyMat);return g;}
 const handheld=new THREE.Group();camera.add(handheld);if(!camera.parent)scene.add(camera);computer(handheld,.42,-.57,-1.2,.7);handheld.visible=false;
 const cart=new THREE.Group();cart.position.set(15,0,8);scene.add(cart);box(cart,2.6,.15,2,0,5.5,0,silver);box(cart,.2,5.5,.2,-1,2.75,-.7);box(cart,.2,5.5,.2,1,2.75,-.7);box(cart,.2,5.5,.2,-1,2.75,.7);box(cart,.2,5.5,.2,1,2.75,.7);const laptop=computer(cart,0,5.65,0,1.4);laptop.traverse(m=>{if(m.isMesh){m.userData={laptop:true};pickables.push(m);}});text(cart,'ENGINEER LAPTOP',0,4.9,1.04,2.2);
 const monitors=[];
 for(const n of nodes.filter(n=>n.type!=='cloud')){
  const serial=['switch','san','firewall'].includes(n.type),rear=n.type==='server'||n.type==='gpu'||n.type==='storage',z=(rear?-1:1)*(n.depth/2+.16);
  const types=serial?[['CONSOLE','Console',0],['SERVICE LAN','Ethernet',1]]:[['SERVICE LAN','Ethernet',1]];
  types.forEach(([name,medium,speed],i)=>{const pos=new THREE.Vector3(-.72+i*.42,0,z),p={name,speed,medium,side:rear?'rear':'front',pos,link:null,service:true};n.ports.push(p);const m=box(n.group,.22,.15,.12,pos.x,pos.y,pos.z,new THREE.MeshBasicMaterial({color:medium==='Console'?0xf2bd71:0x71d4fa}));m.userData={node:n,port:p,servicePort:true};pickables.push(m);const caption=text(n.group,name,pos.x,pos.y+.15,pos.z+(rear?-.09:.09),.7);if(rear)caption.rotation.y=Math.PI;});
 }
 const racks=[...new Set(nodes.filter(n=>n.type==='server'||n.type==='gpu').map(n=>n.rack))];
 for(const rack of racks){const targets=nodes.filter(n=>n.rack===rack&&(n.type==='server'||n.type==='gpu'));const x=targets[0].pos.x;const g=new THREE.Group();g.position.set(x,0,5.15);scene.add(g);box(g,2.4,.15,1.2,0,5.7,0,silver);box(g,.16,5.7,.16,-1,2.85,0);box(g,.16,5.7,.16,1,2.85,0);box(g,2,1.25,.15,0,6.7,-.35);const display=box(g,1.8,1.05,.02,0,6.7,-.26,screenMat);text(g,'SERVER KVM',0,6.85,-.235,1.5);text(g,rack,0,6.5,-.235,1.4);for(let r=0;r<4;r++)for(let c=0;c<14;c++)box(g,.12,.025,.12,-.92+c*.14,5.81,-.1+r*.16,keyMat);g.traverse(m=>{if(m.isMesh){m.userData={monitor:targets,node:targets[0]};pickables.push(m);}});monitors.push({g,targets});}
 document.body.insertAdjacentHTML('beforeend',`<div id="inventory"><button data-slot="0" class="equipped">0 Hands</button><button data-slot="1">1 Console</button><button data-slot="2">2 LAN cable</button><button id="open-laptop">Tab Laptop</button><span id="stance">STANDING</span></div><section id="field-laptop" hidden aria-label="Device inspection laptop"><div class="laptop-top"><strong id="laptop-title">FIELD LAPTOP</strong><button id="close-laptop" aria-label="Close laptop">×</button></div><div class="laptop-info"><span id="laptop-session">NOT CONNECTED</span><button id="detach-laptop">Unplug laptop (X)</button></div><label id="kvm-selector" hidden>Server on this KVM<select id="kvm-node"></select></label><div id="laptop-output" role="log" aria-live="polite"></div><form id="laptop-form"><label for="laptop-command">&gt;</label><input id="laptop-command" autocomplete="off" spellcheck="false" placeholder="Type help"></form><div class="laptop-shortcuts"><button data-cmd="show system">System</button><button data-cmd="show interfaces">Interfaces</button><button data-cmd="show storage">SAN paths</button></div><p>Read-only simulation · Console and service LAN use separate cables · No real OS login or network access</p></section>`);
 function print(value){const p=document.createElement('pre');p.textContent=value;$('laptop-output').append(p);$('laptop-output').scrollTop=$('laptop-output').scrollHeight;}
 function show(){open=true;if(document.pointerLockElement)document.exitPointerLock();$('field-laptop').hidden=false;updateHeader();$('laptop-command').focus();}
 function hide(){open=false;$('field-laptop').hidden=true;}
 function updateHeader(){$('laptop-session').textContent=session?`${session.node.id} · ${session.mode} · ${isOffline(session.node)?'OFFLINE':'CONNECTED'}`:'NOT CONNECTED';$('laptop-title').textContent=session?.mode==='KVM'?'SERVER MONITOR / KEYBOARD':'FIELD LAPTOP';}
 function removeTether(){if(tether){scene.remove(tether);tether.geometry.dispose();tether.material.dispose();tether=null;}}
 function disconnect(){if(session?.port?.attached===session)delete session.port.attached;session=null;removeTether();$('kvm-selector').hidden=true;updateHeader();}
 function equip(value){slot=value;document.querySelectorAll('[data-slot]').forEach(b=>{b.classList.toggle('equipped',+b.dataset.slot===slot);b.setAttribute('aria-pressed',String(+b.dataset.slot===slot));});handheld.visible=walking&&slot!==0;}
 function interact(aim){if(aim?.monitor){disconnect();session={node:aim.monitor[0],mode:'KVM',port:null};$('kvm-node').replaceChildren(...aim.monitor.map(n=>new Option(n.id,n.id)));$('kvm-selector').hidden=false;show();print(serviceCommand('show system',session,ctx));return true;}if(aim?.laptop){show();return true;}if(!slot)return false;
 const n=aim?.node;if(!n)return false;const desired=slot===1?'Console':'Ethernet',p=aim.port??n.ports.find(p=>p.service&&p.medium===desired);
 if(!p?.service||p.medium!==desired){print(slot===1?'Use the orange CONSOLE port on a switch, SAN switch or firewall.':'Use the blue SERVICE LAN port. Optical data ports require different adapters.');show();return true;}
 if(p.attached){if(p.attached===session){show();return true;}print('Port occupied. Disconnect its existing laptop first.');show();return true;}
 disconnect();session={node:n,port:p,mode:slot===1?'SERIAL CONSOLE':'DIRECT SERVICE LAN'};p.attached=session;const lineGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);tether=new THREE.Line(lineGeo,new THREE.LineBasicMaterial({color:slot===1?0xffbe6a:0x70daff}));scene.add(tether);show();print(serviceCommand('show system',session,ctx));return true;
 }
 function run(input){if(input.trim().toLowerCase()==='clear'){$('laptop-output').replaceChildren();return;}print('> '+input);print(serviceCommand(input,session,ctx));}
 $('laptop-form').onsubmit=e=>{e.preventDefault();run($('laptop-command').value);$('laptop-command').value='';};document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>run(b.dataset.cmd));document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>equip(+b.dataset.slot));$('open-laptop').onclick=show;$('close-laptop').onclick=hide;$('detach-laptop').onclick=()=>{disconnect();print('Laptop cable disconnected.');};$('kvm-node').onchange=()=>{if(session?.mode==='KVM'){session.node=byId[$('kvm-node').value];updateHeader();run('show system');}};
 function update(enabled){walking=enabled;if(tether)tether.visible=enabled;handheld.visible=enabled&&slot!==0&&!open;if(open)updateHeader();if(tether&&session){const end=session.port.pos.clone().add(session.node.pos),start=new THREE.Vector3(.1,-.65,-1.3).applyMatrix4(camera.matrixWorld);if(start.distanceTo(end)>18){disconnect();print('Cable disconnected: maximum service lead length exceeded.');return;}const points=[start,start.clone().lerp(end,.5).add(new THREE.Vector3(0,-1,0)),end];const curve=new THREE.CatmullRomCurve3(points);const geometry=new THREE.BufferGeometry().setFromPoints(curve.getPoints(24));tether.geometry.dispose();tether.geometry=geometry;}}
 print('Equip 1 Console or 2 LAN. Aim at a labeled service port and press E. Use 0 Hands to manipulate infrastructure cables. Server KVM screens work directly with E.');
 return {get isOpen(){return open;},get slot(){return slot;},get session(){return session;},equip,show,hide,disconnect,interact,update};
}
